[package]
name = "macaque"
version = "0.1.0"
edition = "2021"
author = "Tom French"
description = "OS"
license = "MIT"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
