[package]
name = "macaque"
version = "0.1.0"
edition = "2021"
author = "Tom French"
description = "Various utilities for Rust OS Dev"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
